// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqubwaskrqvlsjcnsihy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxdWJ3YXNrcnF2bHNqY25zaWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTM5MDAsImV4cCI6MjA2NTQ4OTkwMH0.v_LgbF4Hx7Vf87OI7s3GCey3PheLDRZe3Aa9wN3DtqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);